# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
julia:
  - 1.0  # Latest LTS release
  - 1    # Latest stable release
  - nightly
os:
  - linux
# - windows  # Can't use Travis to test windows because https://github.com/JuliaIO/FFMPEG.jl/issues/14
arch:
  - x64
  - x86
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  # Exclude linux 32-bit and windows 64-bit to reduce the number of jobs
  exclude:
    - os: linux
      arch: x86
    - os: windows
      arch: x64
  include:
    - stage: Documentation
      julia: 1.5
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
